version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pablo
      - POSTGRES_DB=cafe
      - POSTGRES_PASSWORD=cafe1234
    ports:
      - '5432:5432'

volumes:
  postgres_data_volume: